### ISSUE TITLE
Wishlist: --keep-faulty-model

### ISSUE THREAD

**Issue by sabaini** [openstack-charmers/zaza#350] opened 2020-04-22 10:19 UTC
Feature request: most of the time when using "functest-run-suite --keep-model" we're interested in inspecting models with test failures. 

It would be useful to have conditional reaping of models, where only successful models would get destroyed, while those with testing failures or errors would be kept for later inspection.

**Comment by auria** [comment] 2021-08-24 10:54
This can be achieved now by using `functest-run-suite --keep-faulty-model`. When an exception occurs during deployment, the model will be kept. Otherwise, models will be destroyed.

Please confirm if this is the expected behavior and close the issue (I can't :))

**Comment by ajkavanagh** [comment] 2021-08-31 11:31
Closing due to new feature provided in #458 by @auria

**Closed by ajkavanagh** 2021-08-31 11:31 UTC
