### ISSUE TITLE
Zaza does not respect the 'local_overlay_enabled ' key

### ISSUE THREAD

**Issue by camille-rodriguez** [openstack-charmers/zaza#379] opened 2020-07-30 20:23 UTC
I tried to add in my bundle the local_overlay_enabled key, set to False, false, true, True, and the behavior is the same. Zaza deploys the local overlay, which overrides the local charm path. This makes it impossible to edit the bundle.yaml to set a different charm path. Zaza will always look at ../../../<charm-name> for the local charm. 

The only workaround I found is to apply a 2nd overlay myself, which re-writes the custom local charm path desired.

**Comment by Vultaire** [comment] 2020-08-10 21:54
I think I've hit the same bug, although not 100% sure.

I think the problem is with [should_render_local_overlay() in zaza/charm_lifecycle/deploy.py](https://github.com/openstack-charmers/zaza/blob/master/zaza/charm_lifecycle/deploy.py#L251).

If you have a tests/bundles/overlays/local-charm-overlay.yaml.j2 file, then the rendering of the local overlay can be disabled via the local_overlay_enabled key in tests.yaml.

However, if that local-charm-overlay.yaml.j2 file does not exist, and since the charm_name field checked in the other if clause seems to be mandatory, it will always return true.

The workaround for now is to place a no-op local-charm-overlay.yaml.j2 file, after which the local_overlay_enabled key should be respected.

**Comment by AurelienLourot** [comment] 2020-09-15 13:12
I think this has been fixed by #383, closing, thanks!

**Closed by AurelienLourot** 2020-09-15 13:12 UTC
